# Generated by Django 5.1.5 on 2025-01-29 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Data',
        ),
    ]
